"""Subset the site's webfonts and generate their @font-face rules.

The site sets its text in Inter, which is what the vault renders in: the theme's
`--font-default` lists display faces ahead of it that are not installed there
and are not shipped here, so Inter is the entry the stack actually resolves to.
`site-overrides.css` names it first to make that explicit rather than
incidental.

Inter is a *variable* font -- one file spans weights 100-900 -- so two files,
upright and italic, cover every weight the site uses. It is OFL-licensed; the
sources live in `vendor/fonts/`.

Run after adding or replacing a font source:

    .venv/Scripts/python scripts/build_fonts.py

Outputs `public/fonts/*.woff2` and `src/styles/fonts.css`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

# Each face is (source filename, output stem, css font-weight, css font-style).
# A variable font declares a weight *range*, which is why Inter needs only two
# files where a static family needs one per weight. Adding a family here is
# enough to make it selectable with `--family`; only the sources have to be
# dropped into `vendor/fonts/` as well.
FAMILIES: dict[str, dict] = {
    "inter": {
        "css_family": "Inter",
        "faces": [
            ("Inter-Variable.woff2", "inter-variable", "100 900", "normal"),
            ("Inter-Variable-Italic.woff2", "inter-variable-italic", "100 900", "italic"),
        ],
    },
}

DEFAULT_FAMILY = "inter"

# Kept ranges, and why each is needed for *this* vault:
#   Basic Latin + Latin-1     Spanish: á é í ó ú ü ñ ¿ ¡
#   Latin Extended-A          Esperanto: ŝ ĝ ĉ ĵ ĥ ŭ (Saŝa, Miĉjo, Micĵo)
#   General Punctuation       curly quotes, en/em dashes, ellipsis
#   Box Drawing               └ used in the infobox templates (└>Cargo)
#   Geometric Shapes          ◆ the folder-note marker in the sidebar
UNICODE_RANGES = [
    (0x0020, 0x007E),
    (0x00A0, 0x00FF),
    (0x0100, 0x017F),
    (0x0192, 0x0192),
    (0x2000, 0x206F),
    (0x20A0, 0x20BF),
    (0x2190, 0x2193),
    (0x2500, 0x257F),
    (0x25A0, 0x25FF),
    (0xFB00, 0xFB06),
]

CSS_UNICODE_RANGE = (
    "U+0020-007E, U+00A0-00FF, U+0100-017F, U+0192, U+2000-206F, "
    "U+20A0-20BF, U+2190-2193, U+2500-257F, U+25A0-25FF, U+FB00-FB06"
)


def wanted_codepoints() -> set[int]:
    codes: set[int] = set()
    for start, end in UNICODE_RANGES:
        codes.update(range(start, end + 1))
    return codes


def build_face(source: Path, stem: str, out_dir: Path) -> tuple[int, int, int]:
    """Subset and convert one face. Returns (before, after, glyphs kept)."""
    before = source.stat().st_size

    # `recalcTimestamp=False` keeps the source's `head.modified` instead of
    # stamping "now". Without it every run produces different bytes, and the
    # generated fonts show up as a spurious diff on each build.
    font = TTFont(str(source), recalcTimestamp=False)
    available = set(font.getBestCmap())
    keep = sorted(available & wanted_codepoints())

    options = subset.Options()
    options.layout_features = ["*"]  # keep kerning and ligatures
    options.desubroutinize = True
    options.hinting = True
    options.notdef_outline = True
    options.recalc_bounds = True
    options.recalc_timestamp = False
    # Drop name/metadata tables that only matter to desktop font managers.
    options.name_IDs = [1, 2, 3, 4, 6]
    options.drop_tables += ["DSIG"]

    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=keep)
    subsetter.subset(font)

    font.flavor = "woff2"
    destination = out_dir / f"{stem}.woff2"
    font.save(str(destination))
    font.close()

    return before, destination.stat().st_size, len(keep)


def render_css(family: str, faces: list[tuple[str, str, str]]) -> str:
    name = FAMILIES[family]["css_family"]

    blocks = [
        "/* GENERATED by scripts/build_fonts.py -- do not edit.",
        f" * Family: {family}. Sources in vendor/fonts/, subset to the scripts",
        " * this vault writes in. Must load BEFORE the theme so its",
        " * `--font-default` stack resolves to a real face.",
        " *",
        " * Inter is (c) The Inter Project Authors, licensed under the SIL Open",
        " * Font License 1.1 -- https://github.com/rsms/inter",
        " * Subsetting and WOFF2 conversion do not change those terms.",
        " */",
        "",
    ]

    for stem, weight, style in faces:
        blocks.append(
            "@font-face {\n"
            f'  font-family: "{name}";\n'
            f'  src: url("/fonts/{stem}.woff2") format("woff2");\n'
            f"  font-weight: {weight};\n"
            f"  font-style: {style};\n"
            "  font-display: swap;\n"
            f"  unicode-range: {CSS_UNICODE_RANGE};\n"
            "}"
        )

    return "\n".join(blocks) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default="vendor/fonts")
    parser.add_argument("--out", default="public/fonts")
    parser.add_argument("--css", default="src/styles/fonts.css")
    parser.add_argument(
        "--family",
        default=DEFAULT_FAMILY,
        choices=sorted(FAMILIES),
        help="which family to ship",
    )
    args = parser.parse_args(argv)

    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    root = Path(__file__).resolve().parents[1]
    source_dir = root / args.source
    out_dir = root / args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    spec = FAMILIES[args.family]
    built: list[tuple[str, str, str]] = []
    total_before = total_after = 0

    print(f"family: {args.family}")
    for filename, stem, weight, style in spec["faces"]:
        source = source_dir / filename
        if not source.exists():
            print(f"  MISSING {filename}", file=sys.stderr)
            continue
        before, after, glyphs = build_face(source, stem, out_dir)
        total_before += before
        total_after += after
        built.append((stem, weight, style))
        print(f"  {filename:30} {before:>8,} -> {after:>7,} B  ({glyphs} codepoints)")

    if not built:
        print("no faces built", file=sys.stderr)
        return 1

    (root / args.css).write_text(
        render_css(args.family, built), encoding="utf-8", newline="\n"
    )

    # Stale output from a previously selected family would otherwise linger and
    # be served for no reason.
    expected = {f"{stem}.woff2" for stem, _, _ in built}
    removed = 0
    for path in sorted(out_dir.glob("*.woff2")):
        if path.name not in expected:
            path.unlink()
            removed += 1

    print(f"\n  total {total_before:,} -> {total_after:,} bytes")
    print(f"  wrote {args.css} and {len(built)} woff2 file(s)")
    if removed:
        print(f"  pruned {removed} file(s) from a previous family")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
